### ISSUE TITLE
Integrate in (rest of) 'Reinstein functions and setup' stuff

### ISSUE THREAD

**Issue by daaronr** [rethinkpriorities/bookdown-template#4]
https://github.com/rethinkpriorities/how-to-visualize/blob/41ef37cdfc94b4baca1b605c5ab5fe249de3928d/main.R#L29

My idea was '`main.R` runs everything'.
I have this set to put things into a folder called `code`

@WillemSleegers  I think you moved this stuff into the `assets/R` folder. 

Should we either switch it back to being in a 'code' folder, or have the 'main' thing put it elsewhere?

**Comment by WillemSleegers** [comment]
I think we addressed this issue.

**Comment by daaronr** [comment]
Agreed. There’s still a bit of work in actually doing this transfer, but I suppose we could close this as the conceptual issue.

**Comment by daaronr** [comment]
OK, it's fine to have this closed but I still have about 20% of it to do. I'll keep working on it as I go. It's not really a standalone task.

**Comment by WillemSleegers** [comment]
Sure, but it’s also not really part of the template. Probably fits better in the rp r package repo. Or just personal workflow stuff.
